[Interface]
PrivateKey = EOSvTjxvhMvJ55QXFnRfXsHFqFiB8uLr8m64FpWr/Wc=
Address = 10.100.1.1/30
ListenPort = 51820

[Peer]
# Router 634b0035-2bdd-4ed4-b234-b9350928423e
PublicKey = ZvnwEV4/DLox+TgEmCUS0bf/gxuAq58xXiggaOidEjA=
AllowedIPs = 10.100.1.2/32